def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    
        agent any

    tools {
        jdk "JDK17"
        maven "MAVEN3.9"
    }
    
    environment{
        cluster = "vproappprod"
        service = "vproapptask-service-prod"

    }

    stages{

        stage('Promote to Production (Approval)') {
            steps {
                script {
                    echo "The build is ready for Production. Waiting for approval..."
                    input message: "Go for Production Deployment?", ok: "Yes, Deploy Now!"
                }
            }
        }
        stage('Deploy to staging ECS'){
            steps{
                    withAWS(credentials: 'awscreds', region: 'us-east-1') {
                        sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    post {
        always {
            sh 'docker image prune -a -f'
            echo 'Slack Notifications.'
            slackSend channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}

