def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    
        agent any

    tools {
        jdk "JDK17"
        maven "MAVEN3.9"
    }
    
    environment{

        SNAP_REPO = 'vprofile-snapshots'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'admin123'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '172.31.23.46'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'        
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredential ='ecr:us-east-1:awscreds'
        appRegistry = '444339627073.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = "https://444339627073.dkr.ecr.us-east-1.amazonaws.com"
        cluster = "vproappstaging"
        service = "vproapptask-service-uyjiws1a"

    }

    stages{
        stage('Build'){
            steps{
                sh 'mvn -s settings.xml -DskipTests clean install'
            }
            post{
                success {
                    echo "Now Archiving."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        
        stage('Test'){
            steps{
                sh 'mvn -s settings.xml test -DargLine="--add-opens java.base/java.lang=ALL-UNNAMED"'
            }
        }

stage('Sonar Analysis') {
    environment {
        scannerHome = tool "${SONARSCANNER}"
    }
    steps {
        withSonarQubeEnv("${SONARSERVER}") {
            sh """
                export SONAR_SCANNER_OPTS="-Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED"
                
                ${scannerHome}/bin/sonar-scanner \
                -Dsonar.projectKey=vprofile \
                -Dsonar.projectName=vprofile \
                -Dsonar.projectVersion=1.0 \
                -Dsonar.sources=src/ \
                -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                -Dsonar.exclusions=**/*.css \
                -Dsonar.junit.reportsPath=target/surefire-reports/ \
                -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            """
        }
    }
}

        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
                    // true = set pipeline to UNSTABLE, false = don't
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("UploadArtifcat"){
            steps{
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vproapp',
                        classifier: '',
                        file: 'target/vprofile-v2.war',
                        type: 'war']
                    ]
                )
            }
        }

        stage("Build App Image"){
            steps{
                script {
                    sh "docker build -t ${appRegistry}:${BUILD_NUMBER} -f Docker-files/app/Dockerfile ."
                    dockerImage = docker.image("${appRegistry}:${BUILD_NUMBER}")
                }
            }
        }

        stage("Upload App Image"){
            steps{
                script {
                    docker.withRegistry( vprofileRegistry, registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                        }
                }
            }
        }

        // stage("Approval") {
        //     steps {
        //         script {
        //             input message: "Approve Staging Deployment?", ok: "Deploy Now!"
        //         }
        //     }
        // }

        stage("Deploy to staging ECS"){
            steps{
                    withAWS(credentials: 'awscreds', region: 'us-east-1') {
                        sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    post{
        always {
            sh 'docker image prune -f'
            }
    }
    // post {
    //     always {
    //         echo 'Slack Notifications.'
    //         slackSend channel: '#jenkinscicd',
    //             color: COLOR_MAP[currentBuild.currentResult],
    //             message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
    //     }
    // }
}

